#!/usr/bin/env python

##  Copyright (c) 2007-2008 Facebook
##
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##
## See accompanying file LICENSE or visit the Scribe site at:
## http://developers.facebook.com/scribe/

'''scribe_ctrl: A simple script for running and monitoring scribe.'''

import argparse
import sys

from fb303_scripts import *
import thrift
from thrift import protocol, transport
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol


def main():

    parser = argparse.ArgumentParser(description='Control scribe')
    parser.add_argument('command', metavar='COMMAND', nargs=1, help='the command')
    parser.add_argument('-p', '--port', dest='port', type=int, default=1463, help='the port number')
    parser.add_argument('-v', '--validate', action='store_true', default=False)
    parser.add_argument('--keyfile', dest='keyfile', help='ssl key file')
    parser.add_argument('--certfile', dest='certfile', help='ssl cert file')
    parser.add_argument('--cacerts', dest='cacerts', help='ssl cacerts')

    args = parser.parse_args()

    retval = fb303_simple_mgmt.service_ctrl(args.command.pop(),
        args.port,
        trans_factory = TTransport.TFramedTransportFactory(),
        prot_factory = TBinaryProtocol.TBinaryProtocolFactory(),
        validate=args.validate,
        ca_certs=args.cacerts,
        keyfile=args.keyfile,
        certfile=args.certfile)

    sys.exit(retval)


if __name__ == '__main__':
    main()

